### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by estribiyo** [mouton0815/axum-sse-from-channel#1]
I found the example very interesting... however I have been testing and trying to add CORS (I'm learning and I'm very new to Rust) and I have no idea how to deal with that...

After adding the `use`:

```
use tower_http::cors::CorsLayer;
```

I modified it to add the highlighted line:

```
pub fn spawn_http_server(listener: TcpListener, tx_message: MutexSender, mut rx_shutdown: Receiver<()>) -> JoinHandle<()> {
    info!("Spawn HTTP server");
    let router = Router::new()
        .route("/sse", get(sse_handler))
        .layer(CorsLayer::permissive()) <---------------------- PRETENDIG TO ADD THIS LAYER
        .with_state(tx_message);

    tokio::spawn(async move {
        axum::serve(listener, router)
            .with_graceful_shutdown(async move {
                rx_shutdown.recv().await.unwrap();
                info!("Termination signal received, leave HTTP server");
            })
            .await
            .unwrap() // Panic accepted
    })
}
```

After searching for countless alternatives, I can't find a solution so that CORS headers can be added. I have tried to directly manage Hyper, Tower, Axum itself. I have tried converting the data to get the desired result, but have been unable to. I have also played with different versions and tried to browse and read the crate documentation without finding how to do it (Actually I have found countless documentation that tells me how to do it and it should be as it appears in this piece of code, however it does not work) . It gives me the following error:

```
error[E0277]: the trait bound `Cors<Route>: tower_service::Service<axum::http::Request<Body>>` is not satisfied
   --> server/src/http_server.rs:38:16
    |
38  |         .layer(CorsLayer::permissive()) 
    |          ----- ^^^^^^^^^^^^^^^^^^^^^^^ the trait `tower_service::Service<axum::http::Request<Body>>` is not implemented for `Cors<Route>`
    |          |
    |          required by a bound introduced by this call
    |
    = help: the trait `tower_service::Service<http::request::Request<ReqBody>>` is implemented for `Cors<S>`
note: required by a bound in `Router::<S>::layer`
   --> /home/javi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.5/src/routing/mod.rs:278:21
    |
275 |     pub fn layer<L>(self, layer: L) -> Router<S>
    |            ----- required by a bound in this associated function
...
278 |         L::Service: Service<Request> + Clone + Send + 'static,
    |                     ^^^^^^^^^^^^^^^^ required by this bound in `Router::<S>::layer`
```

(In this case is with Axum 0.7.5, but it's the same with all versions I've tried).

Do you know how or where I can or should touch to be able to put the CORS headers?

**Comment by mouton0815** [comment]
Thanks for reaching out. It is strange: I added your change, and it compiled immediately on my side.

Please checkout branch https://github.com/mouton0815/axum-sse-from-channel/tree/cors. Does it compile?

I'm using Axum 0.7.5 as you and Cargo/Rust 1.77.0.

**Comment by estribiyo** [comment]
It also seemed very strange to me... it didn't occur to me to do a `clean`. I was using Axum 0.7 and Rust 1.76, but after doing:

```
rust clean
```

Everything worked normally. Possibly something had been left behind in other compilations and was causing the conflict.

Thank you for your attention and sorry for the inconvenience.

**Comment by mouton0815** [comment]
Nice to hear that you were able to resolve the issue. Happy to help!
